# Generated by Django 6.1.1 on 2026-09-29 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='timetable.subject')),
            ],
            options={
                'ordering': ['subject__sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='timetable.teacher')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timetable.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='timetable.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='timetable.teacher')),
            ],
            options={
                'ordering': ['school_class__sort_order', 'subject__sort_order', 'id'],
                'unique_together': {('school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TemplateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='1=周一 ... 7=周日')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_entries', to='timetable.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_entries', to='timetable.subject')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.scheduletemplate')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_entries', to='timetable.timeslot')),
            ],
            options={
                'ordering': ['school_class__sort_order', 'weekday', 'time_slot__sort_order'],
                'unique_together': {('template', 'school_class', 'weekday', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='写入时对时间段权重的快照，改时间段权重不影响历史', max_digits=6)),
                ('status', models.CharField(choices=[('normal', '正常'), ('invigilation', '监考')], default='normal', max_length=20)),
                ('flag', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], default='normal', help_text='异常标记', max_length=20)),
                ('source', models.CharField(choices=[('template', '模板生成'), ('manual', '手动')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='timetable.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='timetable.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='timetable.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='timetable.timeslot')),
            ],
            options={
                'ordering': ['date', 'school_class__sort_order', 'time_slot__sort_order'],
                'indexes': [models.Index(fields=['date'], name='timetable_c_date_8c9eb6_idx'), models.Index(fields=['teacher', 'date'], name='timetable_c_teacher_56c791_idx')],
                'unique_together': {('date', 'time_slot', 'school_class')},
            },
        ),
    ]
