# Generated by Django 6.1.1 on 2026-10-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesession',
            name='status',
        ),
    ]
