# Generated by Django 6.1.1 on 2026-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='写入时对时间段权重的快照，改时间段权重不影响历史', max_digits=6),
        ),
    ]
