# Generated by Django 6.1.1 on 2026-10-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_seed_report_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='flag',
            field=models.CharField(choices=[('normal', '正常'), ('swap', '换课'), ('substitute', '代课'), ('abnormal', '异常')], default='normal', help_text='异常标记', max_length=20),
        ),
    ]
